name: pysim
channels:
- defaults
dependences:
- python=3.8
# Standard Libraries
- numpy
- scipy
- scikit-learn
- matplotlib
# Dev Libraries
- ipykernel
- pytest
- black
- pip
- mypy
- isort
- pylint
- flake8
