name: pysim
channels:
- defaults
dependences:
- python=3.8
# Standard Libraries
- numpy
- scipy
- scikit-learn
- matplotlib
# Dev Libraries
- ipykernel
- pytest
- black
- pip
- mypy
- isort
- pylint
- flake8
- pip
pip:
  - "git+https://github.com/gregversteeg/NPEET.git"
  - "git+https://github.com/mutualinfo/mutual_info.git"
